/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nilai;

import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane; 
import javax.swing.JTextField;
import javax.swing.RowFilter;
import java.util.List;

/**
 *
 * @author Afa
 */

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
public class nil extends javax.swing.JFrame {

    private DefaultTableModel model;
    koneksi kon;
    String nim,username,nilma,nilipa,nilbind,nilbing;
  
    
    public nil() {
        kon = new koneksi();
         initComponents ( );
             model = new DefaultTableModel ();
             tabel.setModel(model);
             model.addColumn("Nama Siswa");
             model.addColumn("NIM");
             model.addColumn("Nilai Matematika");
             model.addColumn("Nilai IPA");
             model.addColumn("Nilai Bahasa Indonesia");
             model.addColumn("Nilai Bahasa Inggris");
     try{ 
           Statement kt = kon.con.createStatement();
           String sql        = "Select * from siswa ";
           ResultSet res   = kt.executeQuery(sql);
           while(res.next ()){
                String a1 = res.getString("nama"); 
                String a2 = res.getString("nim");
                String a3 = res.getString("matem");
                String a4 = res.getString("ipa");
                String a5 = res.getString("bind");
                String a6 = res.getString("bing");
                String obj[]={a1,a2,a3,a4,a5,a6};
                model.addRow(obj);
            }
            
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
      
    }
private void filter (String query){
    TableRowSorter<DefaultTableModel> car=new TableRowSorter<DefaultTableModel>(model);
    tabel.setRowSorter(car);
    car.setRowFilter(RowFilter.regexFilter(query));
}
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jnilai = new javax.swing.JButton();
        jcari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jm = new javax.swing.JTextField();
        jmata = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "NIM", "Nilai Matematika", "Nilai IPA", "Nilai Bahasa Indonesia", "Nilai Bahasa Inggris"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 700, 330));

        jnilai.setText("Masukkan Nilai");
        jnilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnilaiActionPerformed(evt);
            }
        });
        getContentPane().add(jnilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        jcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcariKeyReleased(evt);
            }
        });
        getContentPane().add(jcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 260, 30));

        jLabel1.setText("CARI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 30));

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, -1, -1));

        jLabel2.setText("Nilai");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 50, 50));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, -1, -1));

        jm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmActionPerformed(evt);
            }
        });
        getContentPane().add(jm, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 100, -1));

        jmata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matem", "IPA", "B.Indonesia", "B.Inggris " }));
        getContentPane().add(jmata, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnilaiActionPerformed
        //DefaultTableModel model = (DefaultTableModel) table.getModel();
        String nil,input = null,masuk;    //modell.setRowCount(0);
        try{
       nil=(String)jmata.getSelectedItem();
       masuk=jm.getText();
       Statement mas = kon.con.createStatement();
       if(nil.equals("Matem")){
        nilma=masuk;
         input= "update siswa set nama='"+username+"',nim='"+nim+"',matem='"+nilma+"',ipa='"+nilipa+"',bind='"+nilbind+"',bing='"+nilbing+"' where nim='"+nim+"'";
    
        JOptionPane.showMessageDialog(null,"Nilai telah terinput");
       }
       if(nil.equals("IPA")){
         nilipa=masuk;
       input= "update siswa set nama='"+username+"',nim='"+nim+"',matem='"+nilma+"',ipa='"+nilipa+"',bind='"+nilbind+"',bing='"+nilbing+"' where nim='"+nim+"'";
        
        JOptionPane.showMessageDialog(null,"Nilai telah terinput");}
        
       if(nil.equals("B.Indonesia")){
           nilbind=masuk;
       input= "update siswa set nama='"+username+"',nim='"+nim+"',matem='"+nilma+"',ipa='"+nilipa+"',bind='"+nilbind+"',bing='"+nilbing+"' where nim='"+nim+"'";
        
        JOptionPane.showMessageDialog(null,"Nilai telah terinput");
       }
       if(nil.equals("B.Inggris")){
           nilbing=masuk;
      input= "update siswa set nama='"+username+"',nim='"+nim+"',matem='"+nilma+"',ipa='"+nilipa+"',bind='"+nilbind+"',bing='"+nilbing+"' where nim='"+nim+"'";
       
        JOptionPane.showMessageDialog(null,"Nilai telah terinput");}
       mas.executeUpdate(input);
       
                
                
       if (model.getRowCount() > 0) {
    for (int i = model.getRowCount() - 1; i > -1; i--) {
        model.removeRow(i);
    }
}
       try{ 
           Statement kt = kon.con.createStatement();
           String sql        = "Select * from siswa ";
           ResultSet res   = kt.executeQuery(sql);
           while(res.next ()){
                String a1 = res.getString("nama"); 
                String a2 = res.getString("nim");
                String a3 = res.getString("matem");
                String a4 = res.getString("ipa");
                String a5 = res.getString("bind");
                String a6 = res.getString("bing");
                String obj[]={a1,a2,a3,a4,a5,a6};
                model.addRow(obj);
            }
            
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
       
        }
        catch (Exception e){ JOptionPane.showMessageDialog(null, e);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jnilaiActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
         int selectedrow=tabel.getSelectedRow();
         DefaultTableModel model=(DefaultTableModel)tabel.getModel();
         
         username=model.getValueAt(selectedrow,0).toString();
         nim=model.getValueAt(selectedrow,1).toString();
         nilma=model.getValueAt(selectedrow,2).toString();
         nilipa=model.getValueAt(selectedrow,3).toString();
         nilbind=model.getValueAt(selectedrow,4).toString();
         nilbing=model.getValueAt(selectedrow,5).toString();
            // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    private void jcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcariKeyReleased
    String c=jcari.getText();
    filter(c);        // TODO add your handling code here:
    }//GEN-LAST:event_jcariKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.setVisible(false);
    new Login().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jcari;
    private javax.swing.JTextField jm;
    private javax.swing.JComboBox<String> jmata;
    private javax.swing.JButton jnilai;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

    private String getText(JTextField jm) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
