/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundri;
import java.awt.Color;
import static java.lang.ProcessBuilder.Redirect.to;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.sql.SQLException;
import javax.accessibility.AccessibleContext;
import javax.swing.JOptionPane;
import java.text.DateFormat;  
import java.text.SimpleDateFormat;  
import java.util.Date;  
import java.util.Calendar;  

/**
 *
 * @author Afa
 */

import javax.swing.table.DefaultTableModel;
public class adm extends javax.swing.JFrame {


    private DefaultTableModel model;
    koneksi kon;
  
  
    
    public adm() {
        kon = new koneksi();
         initComponents ( );
         String to = null,toll=null;
         int h, max=0;
         try{
         Statement kt = kon.con.createStatement();
           String tot = "Select * from  milik";
           ResultSet res   = kt.executeQuery(tot);
           while(res.next ()){
                to = res.getString("total");
                h=Integer.parseInt(to);
                if(h>max)
                    max=h;
            }
           toll=Integer.toString(max);
         }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
            jtot.setText(toll);
             model = new DefaultTableModel ();
             tabel.setModel(model);
             model.addColumn("Tanggal");
             model.addColumn("Pemasukan");
             
     try{ 
         
         //Statement bk = kon.con.createStatement();
           // SimpleDateFormat tglft=new SimpleDateFormat("yyyy-MM-dd");
        //Calendar al=Calendar.getInstance();
        //String tl = tglft.format(al.getTime());
         //  String bd="insert into milik values ('"+tl+"','"+where tgl!='"+tl+"'";
          // ResultSet ct = bk.executeQuery(bd);
           //while(ct.next()){
            //   bk.execute(bd);
          // }
           
            Statement kt = kon.con.createStatement();
           String sql = "Select * from  milik";
           ResultSet res   = kt.executeQuery(sql);
           while(res.next ()){
                String a1 = res.getString("tgl"); 
                String a2 = res.getString("pemasukan"); 
                String obj[]={a1,a2};
                model.addRow(obj);
            }
           
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
      
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jpinjam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Pemasukan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 470, 330));

        jpinjam.setText("Kembali");
        jpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpinjamActionPerformed(evt);
            }
        });
        getContentPane().add(jpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jLabel1.setText("Total Pemasukan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 120, 40));
        getContentPane().add(jtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 90, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpinjamActionPerformed
this.setVisible(false);
       new login().setVisible(true);        //DefaultTableModel model = (DefaultTableModel) table.getModel();
            //modell.setRowCount(0);
              
     
       
        
// TODO add your handling code here:
    }//GEN-LAST:event_jpinjamActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
         
            // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jpinjam;
    private javax.swing.JLabel jtot;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
