/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundri;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.io.FileOutputStream;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.*;
import javax.swing.RowFilter;

/**
 *
 * @author Afa
 */

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
public class ambil extends javax.swing.JFrame {

    private DefaultTableModel model;
    koneksi kon;
    String nama,haga,tgla,tglt,berat,ser,ala;
    
    
    public ambil() {
        kon = new koneksi();
         initComponents ( );
             model = new DefaultTableModel ();
             tabel.setModel(model);
             model.addColumn("Nama");
             model.addColumn("Berat");
             model.addColumn("Harga");
             model.addColumn("Tanggal Taruh");
             model.addColumn("Tanggal Ambil");
             model.addColumn("Alamat");
        
     try{ 
           Statement kt = kon.con.createStatement();
           String sql        = "Select * from basis ";
           ResultSet res   = kt.executeQuery(sql);
           while(res.next ()){
                String a1 = res.getString("nama"); 
                String a2 = res.getString("berat");
                String a3 = res.getString("harga"); 
                String a4 = res.getString("tglt");
                String a5 = res.getString("tgla"); 
                String a6 = res.getString("alamat");
                String obj[]={a1,a2,a3,a4,a5,a6};
                model.addRow(obj);
            }
            
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
      
    }
private void filter (String que){
    TableRowSorter<DefaultTableModel> car=new TableRowSorter<DefaultTableModel>(model);
    tabel.setRowSorter(car);
    car.setRowFilter(RowFilter.regexFilter(que));
}
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jpinjam = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jcari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Berat", "Harga", "Tanggal Taruh", "Tanggal Ambil", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 570, 390));

        jpinjam.setText("Ambil");
        jpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpinjamActionPerformed(evt);
            }
        });
        getContentPane().add(jpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, -1, -1));

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, -1));

        jcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcariKeyReleased(evt);
            }
        });
        getContentPane().add(jcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 260, 30));

        jLabel2.setText("Cari");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpinjamActionPerformed
        try{
         JOptionPane.showMessageDialog(this, "Pakaian telah diambil");
         String to;  
         int harga=0,hargat=0,i = 1,bill = 0,h,max=0;
           Statement kt = kon.con.createStatement();
           String tota = "Select * from  milik";
           ResultSet res   = kt.executeQuery(tota);
           while(res.next ()){
                to = res.getString("total");
                h=Integer.parseInt(to);
                if(h>max)
                    max=h;
            }
            String tgl = null;
            String ht=null;
            String ha = null,tot;
                int n=1;
           Statement kk = kon.con.createStatement();
           String band="Select * from basis where nama ='"+nama+"' AND berat='"+berat+"'AND harga='"+haga+"'AND tgla='"+tgla+"'AND tglt='"+tglt+"' AND alamat='"+ala+"'";
           //String mas="insert into milik values('"+tgl+"','"+ha+"')";
           ResultSet ket = kk.executeQuery(band);
           while(ket.next()){
               tgl=ket.getString("tgla");
               ha=ket.getString("harga");
               ser=ket.getString("serial");
                harga=Integer.parseInt(ha);
               max=max+harga;
               ha=Integer.toString(harga);
               ht=Integer.toString(max);
                
           }
           Statement lang=kon.con.createStatement();
           
          String mas="insert into milik values('"+tgl+"','"+ha+"','"+ht+"')";
          
          lang.executeUpdate(mas);
            
         String hapus="delete from basis where serial='"+ser+"' AND nama ='"+nama+"'AND berat='"+berat+"'AND harga='"+haga+"'AND tgla='"+tgla+"'AND tglt='"+tglt+"'";
         Statement han=kon.con.createStatement();
         han.executeUpdate(hapus);
         Document document= new Document();
         PdfWriter.getInstance(document, new FileOutputStream("Nota.pdf"));
         document.open();
         document.add(new Paragraph("Nama '"+nama+"' Berat '"+berat+"' Harga '"+haga+"' Alamat '"+ala+"'"));
         document.close();
              int SelectedRowIndex=tabel.getSelectedRow();
                model.removeRow(SelectedRowIndex);  
                
            //}
      
       // }
        }
        catch (Exception e){ JOptionPane.showMessageDialog(null, e);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jpinjamActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
         int selectedrow=tabel.getSelectedRow();
         DefaultTableModel model=(DefaultTableModel)tabel.getModel();
         nama=model.getValueAt(selectedrow,0).toString();
         berat=model.getValueAt(selectedrow,1).toString();
         haga=model.getValueAt(selectedrow,2).toString();
         tglt=model.getValueAt(selectedrow,3).toString();
         tgla=model.getValueAt(selectedrow,4).toString();
         ala=model.getValueAt(selectedrow,5).toString();
         
            // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
       new ukur().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcariKeyReleased
    String c=jcari.getText();
    filter(c);
// TODO add your handling code here:
    }//GEN-LAST:event_jcariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ambil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ambil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ambil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ambil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ambil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jcari;
    private javax.swing.JButton jpinjam;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
