/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpus;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.sql.SQLException;
import javax.accessibility.AccessibleContext;
import javax.swing.JOptionPane;
import java.text.DateFormat;  
import java.text.SimpleDateFormat;  
import java.util.Date;  
import java.util.Calendar;  
import javax.swing.RowFilter;

/**
 *
 * @author Afa
 */

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
public class datap extends javax.swing.JFrame {

    private DefaultTableModel model;
    koneksi kon;
    String serial,username,tglpin,tglkem,denda,tgldenda;
  
    
    public datap() {
        kon = new koneksi();
         initComponents ( );
             model = new DefaultTableModel ();
             tabel.setModel(model);
             model.addColumn("Nama Peminjam");
             model.addColumn("Serial Buku");
             model.addColumn("Tanggal Pinjam");
             model.addColumn("Tanggal Pengembalian");
             model.addColumn("Tanggal Dikembalikan");
             model.addColumn("Denda");
     try{ 
           Statement kt = kon.con.createStatement();
           String sql        = "Select * from dipinjam ";
           ResultSet res   = kt.executeQuery(sql);
           while(res.next ()){
                String a1 = res.getString("pnama"); 
                String a2 = res.getString("pserial");
                String a3 = res.getString("tglpin");
                String a4 = res.getString("tglkem");
                String a5 = res.getString("tglden");
                String a6 = res.getString("denda");
                String obj[]={a1,a2,a3,a4,a5,a6};
                model.addRow(obj);
            }
            
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
      
    }
private void filter (String query){
    TableRowSorter<DefaultTableModel> car=new TableRowSorter<DefaultTableModel>(model);
    tabel.setRowSorter(car);
    car.setRowFilter(RowFilter.regexFilter(query));
}
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jpinjam = new javax.swing.JButton();
        jcari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama Peminjam", "Serial Buku", "Tanggal Pinjam", "Tanggal Pengembalian", "Tanggal Dikembalikan", "Denda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 470, 330));

        jpinjam.setText("Hapus");
        jpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpinjamActionPerformed(evt);
            }
        });
        getContentPane().add(jpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        jcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcariKeyReleased(evt);
            }
        });
        getContentPane().add(jcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 260, 30));

        jLabel1.setText("CARI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 30));

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpinjamActionPerformed
        //DefaultTableModel model = (DefaultTableModel) table.getModel();
        String j = null;    //modell.setRowCount(0);
        try{
         Statement hap=kon.con.createStatement();
         String pus="delete from dipinjam where pnama='"+username+"' AND pserial='"+serial+"' AND tglpin ='"+tglpin+"' AND tglkem='"+tglkem+"' AND tglden='"+tgldenda+"' AND denda='"+denda+"' ";
         hap.execute(pus);
         int SelectedRowIndex=tabel.getSelectedRow();
        model.removeRow(SelectedRowIndex);
        Statement st=kon.con.createStatement();
        String kurang="SELECT * FROM buku WHERE serial ='"+serial+"'";
         ResultSet cek = st.executeQuery(kurang);
         cek.next(); 
            if (cek.getRow()==1){
                j=cek.getString("jumlah");
                int  jumlah= Integer.parseInt(j);
                jumlah++;
                j=Integer.toString(jumlah);
            }
       Statement mas = kon.con.createStatement();
        //String keluar="SELECT * FROM buku WHERE serial='"+serial+"'";
         //ResultSet cekseri = mas.executeQuery(keluar);
          String input= "update buku set jumlah='"+j+"' where serial='"+serial+"'";
        mas.executeUpdate(input);
        JOptionPane.showMessageDialog(null,"Buku telah dikembalikan dan Denda telah dibayarkan..");
         //cek.next(); 
           // if (cek.getRow()==1){
                
                
            //}
      
        }
        catch (Exception e){ JOptionPane.showMessageDialog(null, e);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jpinjamActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
         int selectedrow=tabel.getSelectedRow();
         DefaultTableModel model=(DefaultTableModel)tabel.getModel();
         
         username=model.getValueAt(selectedrow,0).toString();
         serial=model.getValueAt(selectedrow,1).toString();
         tglpin=model.getValueAt(selectedrow,2).toString();
         tglkem=model.getValueAt(selectedrow,3).toString();
         tgldenda=model.getValueAt(selectedrow,4).toString();
         denda=model.getValueAt(selectedrow,5).toString();
            // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    private void jcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcariKeyReleased
    String c=jcari.getText();
    filter(c);        // TODO add your handling code here:
    }//GEN-LAST:event_jcariKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.setVisible(false);
    new menuad().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jcari;
    private javax.swing.JButton jpinjam;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
