/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

import java.awt.Color;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Citra Yasin Akbar
 */
public class Kamar extends javax.swing.JFrame {

    /**
     * Creates new form Kamar

*/String username;
    koneksi kon;
    public Kamar() {
        kon = new koneksi();
        initComponents();
    }

    /**
     *
     * 
     * 
     * @param pars
     * 
     */
    public Kamar(String user){
        initComponents();
        kon = new koneksi();
        username=user;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        no1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        no4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        r4 = new javax.swing.JRadioButton();
        no2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        r2 = new javax.swing.JRadioButton();
        no5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        r5 = new javax.swing.JRadioButton();
        no3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        r3 = new javax.swing.JRadioButton();
        no6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        r6 = new javax.swing.JRadioButton();
        pilih = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        no1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setText("No. 01");

        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout no1Layout = new javax.swing.GroupLayout(no1);
        no1.setLayout(no1Layout);
        no1Layout.setHorizontalGroup(
            no1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, no1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(no1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r1)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        no1Layout.setVerticalGroup(
            no1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(r1)
                .addContainerGap())
        );

        getContentPane().add(no1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 70, -1, -1));

        no4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel4.setText("No. 04");

        javax.swing.GroupLayout no4Layout = new javax.swing.GroupLayout(no4);
        no4.setLayout(no4Layout);
        no4Layout.setHorizontalGroup(
            no4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, no4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(no4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r4)
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        no4Layout.setVerticalGroup(
            no4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(r4)
                .addContainerGap())
        );

        getContentPane().add(no4, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 246, -1, -1));

        no2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel2.setText("No. 02");

        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout no2Layout = new javax.swing.GroupLayout(no2);
        no2.setLayout(no2Layout);
        no2Layout.setHorizontalGroup(
            no2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, no2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(no2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r2)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        no2Layout.setVerticalGroup(
            no2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(r2)
                .addContainerGap())
        );

        getContentPane().add(no2, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 70, -1, -1));

        no5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel5.setText("No. 05");

        javax.swing.GroupLayout no5Layout = new javax.swing.GroupLayout(no5);
        no5.setLayout(no5Layout);
        no5Layout.setHorizontalGroup(
            no5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(no5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r5)
                    .addComponent(jLabel5))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        no5Layout.setVerticalGroup(
            no5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(r5)
                .addContainerGap())
        );

        getContentPane().add(no5, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 246, -1, -1));

        no3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setText("No. 03");

        javax.swing.GroupLayout no3Layout = new javax.swing.GroupLayout(no3);
        no3.setLayout(no3Layout);
        no3Layout.setHorizontalGroup(
            no3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, no3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(no3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r3)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        no3Layout.setVerticalGroup(
            no3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(r3)
                .addContainerGap())
        );

        getContentPane().add(no3, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 70, -1, -1));

        no6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel6.setText("No. 06");

        javax.swing.GroupLayout no6Layout = new javax.swing.GroupLayout(no6);
        no6.setLayout(no6Layout);
        no6Layout.setHorizontalGroup(
            no6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, no6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(no6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r6)
                    .addComponent(jLabel6))
                .addContainerGap())
        );
        no6Layout.setVerticalGroup(
            no6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(r6)
                .addContainerGap())
        );

        getContentPane().add(no6, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 246, -1, -1));

        pilih.setText("Pilih");
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });
        getContentPane().add(pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 373, 70, 30));

        jButton1.setText("Cek");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed



// TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
       try{
            if (r1.isSelected()){
            String nama,email,nohp,tanggallahir,noktp,input;
            Statement kt = kon.con.createStatement();
            Statement temp =kon.con.createStatement();
            ResultSet cekkamar = kt.executeQuery("SELECT * FROM ruang WHERE kamar = 1");
            ResultSet ambildata = temp.executeQuery("SELECT * FROM penginap WHERE id='"+username+"'");
            ambildata.next();
            cekkamar.next();
            if(ambildata.getRow()==1){
                nama=ambildata.getString("nama");
                email=ambildata.getString("email");
                nohp=ambildata.getString("nohp");
                tanggallahir=ambildata.getString("tanggallahir");
                noktp=ambildata.getString("noktp");
                input= "update ruang set nama='"+nama+"',email='"+email+"',nohp='"+nohp+"',tanggallahir='"+tanggallahir+"',noktp='"+noktp+"', status='isi' where kamar = 1 "; 
                kt.executeUpdate(input);
                JOptionPane.showMessageDialog(null,nama+""+email+""+nohp);
                this.dispose();
                new Menu(username).setVisible(true);
            }
            else 
                JOptionPane.showMessageDialog(null,"Kamar telah dipesan");
            }
            if (r2.isSelected()){
            String nama,email,nohp,tanggallahir,noktp,input;
            Statement kt = kon.con.createStatement();
            Statement temp =kon.con.createStatement();
            ResultSet cekkamar = kt.executeQuery("SELECT * FROM ruang WHERE kamar = 2");
            ResultSet ambildata = temp.executeQuery("SELECT * FROM penginap WHERE id='"+username+"'");
            ambildata.next();
            cekkamar.next();
            if(ambildata.getRow()==1){
                nama=ambildata.getString("nama");
                email=ambildata.getString("email");
                nohp=ambildata.getString("nohp");
                tanggallahir=ambildata.getString("tanggallahir");
                noktp=ambildata.getString("noktp");
                input= "update ruang set nama='"+nama+"',email='"+email+"',nohp='"+nohp+"',tanggallahir='"+tanggallahir+"',noktp='"+noktp+"', status='isi' where kamar = 2 "; 
                kt.executeUpdate(input);
                JOptionPane.showMessageDialog(null,nama+""+email+""+nohp);
                this.dispose();
                new Menu(username).setVisible(true);
            }
            else 
                JOptionPane.showMessageDialog(null,"Kamar telah dipesan");
            }
            if (r3.isSelected()){
            String nama,email,nohp,tanggallahir,noktp,input;
            Statement kt = kon.con.createStatement();
            Statement temp =kon.con.createStatement();
            ResultSet cekkamar = kt.executeQuery("SELECT * FROM ruang WHERE kamar = 3");
            ResultSet ambildata = temp.executeQuery("SELECT * FROM penginap WHERE id='"+username+"'");
            ambildata.next();
            cekkamar.next();
            if(ambildata.getRow()==1){
                nama=ambildata.getString("nama");
                email=ambildata.getString("email");
                nohp=ambildata.getString("nohp");
                tanggallahir=ambildata.getString("tanggallahir");
                noktp=ambildata.getString("noktp");
                input= "update ruang set nama='"+nama+"',email='"+email+"',nohp='"+nohp+"',tanggallahir='"+tanggallahir+"',noktp='"+noktp+"', status='isi' where kamar = 3 "; 
                kt.executeUpdate(input);
                JOptionPane.showMessageDialog(null,nama+""+email+""+nohp);
                this.dispose();
                new Menu(username).setVisible(true);
            }
            else 
                JOptionPane.showMessageDialog(null,"Kamar telah dipesan");
            }
            if (r4.isSelected()){
            String nama,email,nohp,tanggallahir,noktp,input;
            Statement kt = kon.con.createStatement();
            Statement temp =kon.con.createStatement();
            ResultSet cekkamar = kt.executeQuery("SELECT * FROM ruang WHERE kamar = 4");
            ResultSet ambildata = temp.executeQuery("SELECT * FROM penginap WHERE id='"+username+"'");
            ambildata.next();
            cekkamar.next();
            if(ambildata.getRow()==1){
                nama=ambildata.getString("nama");
                email=ambildata.getString("email");
                nohp=ambildata.getString("nohp");
                tanggallahir=ambildata.getString("tanggallahir");
                noktp=ambildata.getString("noktp");
                input= "update ruang set nama='"+nama+"',email='"+email+"',nohp='"+nohp+"',tanggallahir='"+tanggallahir+"',noktp='"+noktp+"', status='isi' where kamar = 4 "; 
                kt.executeUpdate(input);
                JOptionPane.showMessageDialog(null,nama+""+email+""+nohp);
                this.dispose();
                new Menu(username).setVisible(true);
            
            }
            else 
                JOptionPane.showMessageDialog(null,"Kamar telah dipesan");
            }
            if (r5.isSelected()){
            String nama,email,nohp,tanggallahir,noktp,input;
            Statement kt = kon.con.createStatement();
            Statement temp =kon.con.createStatement();
            ResultSet cekkamar = kt.executeQuery("SELECT * FROM ruang WHERE kamar = 5");
            ResultSet ambildata = temp.executeQuery("SELECT * FROM penginap WHERE id='"+username+"'");
            ambildata.next();
            cekkamar.next();
            if(ambildata.getRow()==1){
                nama=ambildata.getString("nama");
                email=ambildata.getString("email");
                nohp=ambildata.getString("nohp");
                tanggallahir=ambildata.getString("tanggallahir");
                noktp=ambildata.getString("noktp");
                input= "update ruang set nama='"+nama+"',email='"+email+"',nohp='"+nohp+"',tanggallahir='"+tanggallahir+"',noktp='"+noktp+"', status='isi' where kamar =5 "; 
                kt.executeUpdate(input);
                JOptionPane.showMessageDialog(null,nama+""+email+""+nohp);
                this.dispose();
                new Menu(username).setVisible(true);
            
            }
            else 
                JOptionPane.showMessageDialog(null,"Kamar telah dipesan");
            }
            if (r6.isSelected()){
            String nama,email,nohp,tanggallahir,noktp,input;
            Statement kt = kon.con.createStatement();
            Statement temp =kon.con.createStatement();
            ResultSet cekkamar = kt.executeQuery("SELECT * FROM ruang WHERE kamar = 6");
            ResultSet ambildata = temp.executeQuery("SELECT * FROM penginap WHERE id='"+username+"'");
            ambildata.next();
            cekkamar.next();
            if(ambildata.getRow()==1){
                nama=ambildata.getString("nama");
                email=ambildata.getString("email");
                nohp=ambildata.getString("nohp");
                tanggallahir=ambildata.getString("tanggallahir");
                noktp=ambildata.getString("noktp");
                input= "update ruang set nama='"+nama+"',email='"+email+"',nohp='"+nohp+"',tanggallahir='"+tanggallahir+"',noktp='"+noktp+"', status='isi' where kamar = 6 "; 
                kt.executeUpdate(input);
                JOptionPane.showMessageDialog(null,nama+""+email+""+nohp);
                this.dispose();
                new Menu(username).setVisible(true);
            }
            else 
                JOptionPane.showMessageDialog(null,"Kamar telah dipesan");
            }
            /*if (cekkamar.getRow()==1){ 
                if(cekkamar.getString("status").equals("kosong")){
                
                PreparedStatement st = kon.con.prepareStatement(input);
                //st.setString(1,nama);
                //st.setString(2,email);
                //st.setString(3,nohp);
                //st.setString(4,tanggallahir);
                //st.setString(5,noktp);
                //st.setString(6,"isi");
                st.executeUpdate();
             
                JOptionPane.showMessageDialog(null, "Pesanan anda akan di proses ");                
                this.dispose();
                
            }
                else {
                JOptionPane.showMessageDialog(null, "Maaf, Kamar telah digunakan");
                r1.setSelected(false);
                    }
                 }
            
            //batas 
            }
            if (r2.isSelected()){
                String masuk = "SELECT * FROM ruang WHERE kamar= 2";
                Statement kt = kon.con.createStatement();
                ResultSet cekkamar = kt.executeQuery(masuk);
                cekkamar.next();
            if (cekkamar.getRow()==1){   
                String input= "update ruang set status=? where kamar = 2"; 
                if(cekkamar.getString("status").equals("kosong")){
                PreparedStatement st = kon.con.prepareStatement(input);
                st.setString(1,"isi");
                st.executeUpdate();
                st.close();
                kon.con.close();
                JOptionPane.showMessageDialog(null, "Pesanan anda akan di proses ");                
                this.dispose();
                
            }
                else {
                JOptionPane.showMessageDialog(null, "Maaf, Kamar telah digunakan");
                r2.setSelected(false);
                    }
                 }
            
        //batas 
       }
            if (r3.isSelected()){
                String masuk = "SELECT * FROM ruang WHERE kamar= 3";
                Statement kt = kon.con.createStatement();
                ResultSet cekkamar = kt.executeQuery(masuk);
            cekkamar.next();
            if (cekkamar.getRow()==1){   
                String input= "update ruang set status=? where kamar = 3"; 
                if(cekkamar.getString("status").equals("kosong")){
                PreparedStatement st = kon.con.prepareStatement(input);
                st.setString(1,"isi");
                st.executeUpdate();
                st.close();
                kon.con.close();
                JOptionPane.showMessageDialog(null, "Pesanan anda akan di proses ");                
                this.dispose();
                
            }
                else {
                JOptionPane.showMessageDialog(null, "Maaf, Kamar telah digunakan");
                r3.setSelected(false);
                    }
                 }
            }
            //batas
            
            if (r4.isSelected()){
                String masuk = "SELECT * FROM ruang WHERE kamar= 4";
                Statement kt = kon.con.createStatement();
                ResultSet cekkamar = kt.executeQuery(masuk);
            cekkamar.next();
            if (cekkamar.getRow()==1){   
                String input= "update ruang set status=? where kamar = 4"; 
                if(cekkamar.getString("status").equals("kosong")){
                PreparedStatement st = kon.con.prepareStatement(input);
                st.setString(1,"isi");
                st.executeUpdate();
                st.close();
                kon.con.close();
                JOptionPane.showMessageDialog(null, "Pesanan anda akan di proses ");                
                this.dispose();
                
            }
                else {
                JOptionPane.showMessageDialog(null, "Maaf, Kamar telah digunakan");
                r4.setSelected(false);
                    }
                 }
            }
            
            //batas
           
            if (r5.isSelected()){
                String masuk = "SELECT * FROM ruang WHERE kamar= 5";
                Statement kt = kon.con.createStatement();
                ResultSet cekkamar = kt.executeQuery(masuk);
            cekkamar.next();
            if (cekkamar.getRow()==1){   
                String input= "update ruang set status=? where kamar = 5"; 
                if(cekkamar.getString("status").equals("kosong")){
                PreparedStatement st = kon.con.prepareStatement(input);
             7   st.setString(1,"isi");
                st.executeUpdate();
                st.close();
                kon.con.close();
                JOptionPane.showMessageDialog(null, "Pesanan anda akan di proses ");                
                this.dispose();
                
            }
                else {
                JOptionPane.showMessageDialog(null, "Maaf, Kamar telah digunakan");
                r5.setSelected(false);
                    }
                 }
            }
            //batas
            
            if (r6.isSelected()){
                String masuk = "SELECT * FROM ruang WHERE kamar= 6";
                Statement kt = kon.con.createStatement();
                ResultSet cekkamar = kt.executeQuery(masuk);
            cekkamar.next();
            if (cekkamar.getRow()==1){  
                
                String input= "update ruang set status=? where kamar = 6"; 
                if(cekkamar.getString("status").equals("kosong")){
                PreparedStatement st = kon.con.prepareStatement(input);
                st.setString(1,"isi");
                st.executeUpdate();
                st.close();
                kon.con.close();
                JOptionPane.showMessageDialog(null, "Pesanan anda akan di proses ");                
                this.dispose();
                
            }
                else {
                no6.setBackground(Color.GREEN);
                JOptionPane.showMessageDialog(null, "Maaf, Kamar telah digunakan");
                r6.setSelected(false);
                    }
                 }*/
            
       }
        catch(SQLException e){JOptionPane.showMessageDialog(this, "SALAH GOBLOK"+e.getMessage());}// TODO add your handling code here:
    }//GEN-LAST:event_pilihActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
        String query = "select * from ruang where kamar=1";
        
        Statement kt,q1,q2,q3,q4,q5,q6;
        kt = kon.con.createStatement();
        q1 = kon.con.createStatement();
        q2 = kon.con.createStatement();
        q3 = kon.con.createStatement();
        q4 = kon.con.createStatement();
        q5 = kon.con.createStatement();
        q6 = kon.con.createStatement();
        ResultSet cekkamar = kt.executeQuery(query);
        ResultSet cekkamar1 = q1.executeQuery("SELECT * FROM ruang WHERE kamar=1");
        ResultSet cekkamar2 = q2.executeQuery("SELECT * FROM ruang WHERE kamar =2");
        ResultSet cekkamar3 = q3.executeQuery("SELECT * FROM ruang WHERE kamar =3");
        ResultSet cekkamar4 = q4.executeQuery("SELECT * FROM ruang WHERE kamar =4");
        ResultSet cekkamar5 = q5.executeQuery("SELECT * FROM ruang WHERE kamar =5");
        ResultSet cekkamar6 = q6.executeQuery("SELECT * FROM ruang WHERE kamar =6");
        cekkamar1.next();
        cekkamar2.next();
        cekkamar3.next();
        cekkamar4.next();
        cekkamar5.next();
        cekkamar6.next();
        
        
        while(cekkamar.next()){
            if (cekkamar.getRow()==1){
                if(cekkamar1.getString("status").equals("kosong")){                     
                no1.setBackground(Color.GREEN);}
                else 
                no1.setBackground(Color.RED);
            
                 
                if(cekkamar2.getString("status").equals("kosong"))
                no2.setBackground(Color.GREEN);
                else 
                no2.setBackground(Color.RED);
                    
         
           
                if(cekkamar3.getString("status").equals("kosong"))
                no3.setBackground(Color.GREEN);
                else 
                no3.setBackground(Color.RED);
                    
  
   
       
                if(cekkamar4.getString("status").equals("kosong"))
                no4.setBackground(Color.GREEN);

                else 
                no4.setBackground(Color.RED);
                    

      
          
                if(cekkamar5.getString("status").equals("kosong"))
                no5.setBackground(Color.GREEN);
                else 
                no5.setBackground(Color.RED);
                    
 
  
                if(cekkamar6.getString("status").equals("kosong"))
                no6.setBackground(Color.GREEN);
                else 
                no6.setBackground(Color.RED);
                    
            }
       }
        } catch(SQLException e){JOptionPane.showMessageDialog(this, "SALAH GOBLOK"+e.getMessage());}         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kamar().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private java.awt.List list1;
    private javax.swing.JPanel no1;
    private javax.swing.JPanel no2;
    private javax.swing.JPanel no3;
    private javax.swing.JPanel no4;
    private javax.swing.JPanel no5;
    private javax.swing.JPanel no6;
    private javax.swing.JButton pilih;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    // End of variables declaration//GEN-END:variables
}
