/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.sql.SQLException;
import javax.accessibility.AccessibleContext;
import javax.swing.JOptionPane;
/**
 *
 * @author Hasvi
 */

import javax.swing.table.DefaultTableModel;
public class Resepsionis extends javax.swing.JFrame {

    private DefaultTableModel model;
    private DefaultTableModel modell;
    koneksi kon;
    String nama,email,nohp,tanggallahir,noktp,kamar;
    
    
    public Resepsionis() {
        kon = new koneksi();
         initComponents ( );
             model = new DefaultTableModel ();
             tabel.setModel(model);
             model.addColumn("Nama");
             model.addColumn("Email");
             model.addColumn("No.Hp");
             model.addColumn("Tgl Lahir");
             model.addColumn("No.KTP");     
             model.addColumn("Kamar");
             
             modell = new DefaultTableModel ();
             tabel2.setModel(modell);
             modell.addColumn("Nama");
             modell.addColumn("Email");
             modell.addColumn("No.Hp");
             modell.addColumn("Tgl Lahir");
             modell.addColumn("No.KTP");     
             modell.addColumn("Kamar");
     try{ 
           Statement kt = kon.con.createStatement();
           String sql        = "Select * from ruang where (status='isi' XOR nama=' ') XOR (status='kosong' and  nama=' ')";
           ResultSet res   = kt.executeQuery(sql);
           while(res.next ()){
                String a1 = res.getString("nama"); 
                String a2 = res.getString("email");
                String a3 = res.getString("nohp"); 
                String a4 = res.getString("Tanggallahir");
                String a5 = res.getString("noktp"); 
                String a6 = res.getString("kamar");
                String obj[]={a1,a2,a3,a4,a5,a6};
                model.addRow(obj);
            }
             
    
           Statement zt = kon.con.createStatement();
           String sst= "select * from booked ";
           ResultSet rs= zt.executeQuery(sst);
           while(rs.next ()){
                String b1 = rs.getString("nama"); 
                String b2 = rs.getString("email");
                String b3 = rs.getString("nohp"); 
                String b4 = rs.getString("tanggallahir");
                String b5 = rs.getString("noktp"); 
                String b6 = rs.getString("kamar");
                String ob[]={b1,b2,b3,b4,b5,b6};
                modell.addRow(ob);
            }
           
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "Email", "Tanggal Lahir", "No KTP", "No Kamar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 160));

        jButton1.setText("Pindah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 154, -1, -1));

        tabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 450, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //DefaultTableModel model = (DefaultTableModel) table.getModel();
            modell.setRowCount(0);
        try{
           DefaultTableModel model1=(DefaultTableModel)tabel.getModel();
        int SelectedRowIndex=tabel.getSelectedRow();
        model.removeRow(SelectedRowIndex);
        
         String masuk = "insert into booked values('"+nama+"','"+email+"','"+nohp+"','"+tanggallahir+"','"+noktp+"','"+kamar+"')";
          Statement st = kon.con.createStatement();
         st.executeUpdate(masuk);
         
         String keluar="SELECT * FROM ruang WHERE kamar='"+kamar+"'";
         ResultSet cekkamar = st.executeQuery(keluar);
         String input= "update ruang set nama=' ',email=' ',nohp=' ',tanggallahir=' ',noktp=' ',kamar='"+kamar+"',status='isi'  where kamar ='"+kamar+"' ";
         
          PreparedStatement kt = kon.con.prepareStatement(input);
            cekkamar.next();
             if (cekkamar.getRow()==1){
                kt.executeUpdate();
                JOptionPane.showMessageDialog(null,"BOOKED!!");
                }
               
           String sql = "Select * from booked ";
           ResultSet res   = kt.executeQuery(sql);
           while(res.next ()){
                String a1 = res.getString("nama"); 
                String a2 = res.getString("email");
                String a3 = res.getString("nohp"); 
                String a4 = res.getString("tanggallahir");
                String a5 = res.getString("noktp"); 
                String a6 = res.getString("kamar");
                String obj[]={a1,a2,a3,a4,a5,a6};
                modell.addRow(obj);
            }
     
      
        }
        catch (Exception e){ JOptionPane.showMessageDialog(null, e);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
         int selectedrow=tabel.getSelectedRow();
         DefaultTableModel model=(DefaultTableModel)tabel.getModel();
         nama=model.getValueAt(selectedrow,0).toString();
         email=model.getValueAt(selectedrow,1).toString();
         nohp=model.getValueAt(selectedrow,2).toString();
         tanggallahir=model.getValueAt(selectedrow,3).toString();
         noktp=model.getValueAt(selectedrow,4).toString();
         kamar=model.getValueAt(selectedrow,5).toString();
         
            // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resepsionis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resepsionis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resepsionis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resepsionis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resepsionis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tabel2;
    // End of variables declaration//GEN-END:variables
}
