/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Afa Fadhlika
 */
public class Pengaturan extends javax.swing.JFrame {

    /**
     * Creates new form Pengaturan
     */
    koneksi kon;
    public Pengaturan() {
        kon = new koneksi();
        initComponents();
         int sed=0,nw;
        try{String d="SELECT * FROM jalan";
            Statement ng=kon.con.createStatement();
            ResultSet ber=ng.executeQuery(d);
            ber.next();
            while(ber.next()){
                sed=ber.getInt("sedang");
            }
            System.out.println(sed);
        }
        catch(SQLException e){
        JOptionPane.showMessageDialog(this, "SALAH GOBLOK");
        System.out.println(e.getErrorCode() + e.getMessage());
        }
        System.out.println(sed);
        String angka = Integer.toString(sed);
        tnow.setText(angka);
        tnow.setEditable(false);   
        
        nw=sed+1;
        String num=Integer.toString(nw);
        tnext.setText(num);
        tnext.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tnow = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tnext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        skip = new javax.swing.JButton();
        D = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tnow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnowActionPerformed(evt);
            }
        });

        jLabel1.setText("Antrian Sekarang");

        tnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnextActionPerformed(evt);
            }
        });

        jLabel2.setText("Antrian Selanjutnya");

        next.setText("Selanjutnya");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        skip.setText("Lewati");

        D.setText("Data");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tnow, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(tnext, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(skip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(next)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tnow, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnext, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next)
                    .addComponent(skip))
                .addGap(18, 18, 18)
                .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnowActionPerformed

    private void tnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnextActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
 this.dispose();
new database().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_DActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
    int bok = 0,ant=0;
        try{String d="SELECT * FROM jalan";
            Statement ng=kon.con.createStatement();
            ResultSet ber=ng.executeQuery(d);
            ber.next();
            while(ber.next()){
                bok=ber.getInt("sedang");
            }
            String antri="SELECT * FROM antri";
            Statement antr=kon.con.createStatement();
            ResultSet no=antr.executeQuery(antri);
            no.next();
            while(no.next()){
                ant=no.getInt("Antri");}
            if(bok<ant){
            bok=bok+1;
            System.out.println(bok);
            String input="insert into jalan values ('"+bok+"')";
            Statement st=kon.con.createStatement();
            st.executeUpdate(input);
            JOptionPane.showMessageDialog(this, "Antrian dilewati");
            
            int sed=6,nw;
            String a="SELECT * FROM jalan";
            Statement g=kon.con.createStatement();
            ResultSet r=g.executeQuery(a);
            r.next();
            while(r.next()){
                sed=r.getInt("sedang");
            }
            System.out.println(sed);
        
        System.out.println(sed);
        String angka = Integer.toString(sed);
        tnow.setText(angka);
        tnow.setEditable(false);   
        
        nw=sed+1;
        String num=Integer.toString(nw);
        tnext.setText(num);
        tnext.setEditable(false);}
        else
            JOptionPane.showMessageDialog(this, "Antrian telah habis");
        }
        catch(SQLException e){
        JOptionPane.showMessageDialog(this, "SALAH GOBLOK");
        System.out.println(e.getErrorCode() + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengaturan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton D;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton next;
    private javax.swing.JButton skip;
    private javax.swing.JTextField tnext;
    private javax.swing.JTextField tnow;
    // End of variables declaration//GEN-END:variables
}
